### ISSUE TITLE
Knobs panel not displayed

### ISSUE THREAD

**Issue by arthakdoo** [kadirahq/storybook-addon-knobs#100]
I am running a storybook instance and have the component displayed there, but knobs panel is not displayed. The source is very simple:

```
import React from 'react';
import {addDecorator, storiesOf} from '@storybook/react';
import HotelList from './HotelList';
import {withKnobs, text} from '@storybook/addon-knobs';

const stories = storiesOf('HotelList', module);
stories.addDecorator(withKnobs);
stories.add('No params', () =>
        <HotelList buttonTitle={text('Button title', 'Ok')}
                   loadResults={action('loadResults')}/>
);
```

No error is shown, console is clear of any messages, it displays the component with the default button text ('Ok'), but knobs panel is not visible anywhere to enable changing the button title.

What's strange, I use storybook at work, and the knobs panel is displayed there, but here on my computer at home, there is no knobs panel.

**Comment by psimyn** [comment]
has the pane been resized to be very small?  CHeck for draggable grey bar on either the very right or bottom of your screen?

**Comment by shilman** [comment]
Guys, this repo is deprecated. Please carry on the conversation over in https://github.com/storybooks/storybook/

Closing this.
