### ISSUE TITLE
not working on local server under windows

### ISSUE THREAD

**Issue by UsulPro** [kadirahq/storybook-addon-knobs#20]
#### First of all thank you for one more great tool for React development! :clap:

I tried to imlement this plug-in and got the following issues:

1. I see new KNOBS panel but nothing inside there
2. the ACTIONS panel was dissapead after that

finaly i deployed my storybook to GP and there i found my property list in KNOP panel. That's why i suppose problem in my os, meaning this warning during plug-in installation:
~~~
λ npm i -D @kadira/storybook-addon-knobs
react-material-color-picker@0.9.2 E:\DevelopWeb\_CompFactory\react-material-color-picker
`-- @kadira/storybook-addon-knobs@1.0.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
~~~
_the same thing during installation react-storybook-addon-info but everything works fine_

#### But is it expected behavior with ACTIONS panel? May be need to register it like this?
`
// .storybook/addons.js
import '@kadira/storybook-addon-knobs/register'
`

Could you help me to solve this?
#### few details
[here my deployed storybook](https://sm-react.github.io/react-material-color-picker/?knob-initColor=%239ccc65&knob-submitLabel=OK&knob-resetLabel=Cansel&selectedKind=Material%20Color%20Picker&selectedStory=play%20with%20props&full=0&down=1&left=1&panelRight=0&downPanel=kadirahq%2Fstorybook-addon-knobs) and [this is my code of this page](https://github.com/sm-react/react-material-color-picker/blob/master/src/stories/index.js#L92)

windows: `Microsoft Windows [Version 6.3.9600]`
package:
~~~
npm list --depth 0

react-material-color-picker@0.9.3 
+-- @kadira/react-storybook-addon-info@3.2.1
+-- @kadira/storybook@2.13.0
+-- @kadira/storybook-addon-knobs@1.0.1
+-- babel-cli@6.14.0
+-- babel-core@6.14.0
+-- babel-eslint@6.1.2
+-- babel-loader@6.2.5
+-- babel-plugin-transform-runtime@6.15.0
+-- babel-polyfill@6.13.0
+-- babel-preset-es2015@6.14.0
+-- babel-preset-react@6.11.1
+-- babel-preset-stage-2@6.13.0
+-- babel-runtime@6.11.6
+-- chai@3.5.0
+-- enzyme@2.4.1
+-- eslint@2.13.1
+-- eslint-config-airbnb@7.0.0
+-- eslint-plugin-babel@3.3.0
+-- eslint-plugin-jsx-a11y@0.6.2
+-- eslint-plugin-react@4.3.0
+-- git-url-parse@6.0.5
+-- jsdom@8.5.0
+-- mocha@2.5.3
+-- react@15.3.1
+-- react-addons-test-utils@15.3.1
+-- react-dom@15.3.1
`-- sinon@1.17.5
~~~

**Comment by roonyh** [comment]
Oh, yeah, you have to register the default addons explicitly when you add an addons.js file. 

In addons.js do following..
```
import '@kadira/storybook-addon-knobs/register' 
import '@kadira/storybook/addons'
```
This should take care of the missing actions panel.

Not sure whats causing the other issue. `fsevents` is an os-x only module according to [this](https://github.com/strongloop/fsevents/issues/118).

Try to update npm if you are using an older version.

also try removing the node_modules folder and doing `npm install --no-optional`.

Will take a look.

**Comment by UsulPro** [comment]
Great! It worked :thumbsup:
actions panel appeared after adding this line. It seems that the presence of even an empty addons.js overrides the default settings.
And the problem with the local server turned out to be that is not enough simply to restart the server, and refresh the page. You need to re-enter the local address `http://localhost:9001/`

Thank you a lot, @roonyh!
