### ISSUE TITLE
need to re-render story at changing a prop value

### ISSUE THREAD

**Issue by UsulPro** [kadirahq/storybook-addon-knobs#22]
because if props used in constructor so it didn't update during and after editing.  But it will change if you refresh a page or select another story and come back. It turns out it looks like a bug

**Comment by arunoda** [comment]
It's not a bug. React's constructor only get called when the component is rendered initially.
Your component should handle props with [componentWillReceiveProps](https://facebook.github.io/react/docs/component-specs.html#updating-componentwillreceiveprops) or something like that.

**Comment by ritz078** [comment]
@arunoda Is there any way I can re-render the story on changing of any knob ? Sometimes it may be needed when you are making a performant component where not every prop change triggers the render of the component.
