### ISSUE TITLE
Option to enable default actions addon alongside knobs

### ISSUE THREAD

**Issue by markoshust** [kadirahq/storybook-addon-knobs#24]
There doesn't appear to be a way to enable the actions addon (https://github.com/kadirahq/storybook-addon-actions#getting-started) and the knobs addon at the same time.

**Comment by arunoda** [comment]
Okay. It's a documentation issue. Will fix it. 
For now check our addon docs for a quick fix.

**Comment by arunoda** [comment]
Check the docs now. I've updated it.
https://github.com/kadirahq/storybook-addon-actions#getting-started

**Comment by markoshust** [comment]
Great. I think the correct link is knobs docs though https://github.com/kadirahq/storybook-addon-knobs#getting-started (in case anyone else finds this thread).
