### ISSUE TITLE
Add TypeScript definitions (as per StoryBook)

### ISSUE THREAD

**Issue by philcockfield** [kadirahq/storybook-addon-knobs#33]
Would be great to have typescript definitions for this add-on, like the main StoryBook module has:

https://github.com/kadirahq/react-storybook/blob/master/config/storybook.d.ts

**Comment by arunoda** [comment]
Cool. We are not really good at TS :) Would happy to have a PR for this.
Core API lives here: https://github.com/kadirahq/storybook-addon-knobs/blob/master/src/index.js

**Comment by roonyh** [comment]
Done in #65
