### ISSUE TITLE
Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option

### ISSUE THREAD

**Issue by sachse** [kadirahq/storybook-addon-knobs#43]
I've ben using a select knob and although it's working well there's a console warning saying `Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.`

**Comment by arunoda** [comment]
I think [this is the line](https://github.com/kadirahq/storybook-addon-knobs/blob/master/src/components/types/Select.js#L21) which cause the error.

We can safely remove that to fix this error.

**Comment by roonyh** [comment]
v1.2.3 should have this fixed.
