### ISSUE TITLE
Date knob dosen't update value

### ISSUE THREAD

**Issue by erisnuts** [kadirahq/storybook-addon-knobs#48]
I'm defining date knob with default value:
`    
const _freeFrom = date('Free from', moment().add(20, 'days').toDate());
console.log(_freeFrom); //prints "Tue Oct 18 2016 17:35:07 GMT+0500 (YEKT)" for today
`
When I'm trying to set up another date, it's just changes back to default, prints same result, widget dosen't update.

help, please!

**Comment by arunoda** [comment]
That's because when you run your code, everything the defaultValue for date gets change.
Try to normalise this date: `moment().add(20, 'days').toDate()` by removing seconds.

**Comment by erisnuts** [comment]
thank you, it helped!
