### ISSUE TITLE
The "knobs" panel not updating when you change to a story with no knobs

### ISSUE THREAD

**Issue by alexmorleyfinch** [kadirahq/storybook-addon-knobs#49]
I've just included this addon in my storybook.

When I change stories using the navigation bar on the left, the "Knobs" interface is only updated if the story that is clicked on also contains knobs. If the story that I click on has no knobs defined, rather than the "No Knobs" interface appearing, the previous knobs panel remains on screen.

E.G. 

Story 1 (with knobs)
Story 2 (without knobs)

How to reproduce the bug:
 - click on Story 2 and the "Knobs" panel shows "No Knobs", as expected.
 - click on Story 1 and the "Knobs" panel shows the knobs for Story 1, as expected.
 - click on Story 2 again and the "Knobs" panel still shows the knobs for Story 1, when it should display "No Knobs".

I have noticed that my "Knobs" panel is at the bottom, next to "Action Logger", as opposed to in it's own separate panel (as appears in the documentation). Maybe this has something to do with it? I am not sure.

I should mention that I am using `stories.addDecorator(withKnobs)` to bind the knobs to my stories, and not the global method.

**Comment by roonyh** [comment]
Yeah, we looking for a way to address this. See #23. Basically you need to have the decorator in every story to avoid this. So for now you will have to add the decorator globally.

> I have noticed that my "Knobs" panel is at the bottom, next to "Action Logger"

Its normal that panels added by addons appear next to each other in bottom. In the storybook shown in documentation panel position is toggled to right. Press `ctrl` + `shift` + `J` to do it.

**Comment by alexmorleyfinch** [comment]
I will add it globally then, thanks for the reply

**Comment by roonyh** [comment]
Sure. I will close this since we are tracking new developments on this at #23.
