### ISSUE TITLE
Allow null for knobs

### ISSUE THREAD

**Issue by Bamieh** [kadirahq/storybook-addon-knobs#54]
It would be nice to enable adding a `null` for the knobs, especially for the dates.

for example, i have a calendar with a start date set to null or an actual date.
```javascript
<MyCalendar
    startDate={date('startDate', null)}
/>
```

> TypeError: Cannot read property 'getTime' of null

**Comment by arunoda** [comment]
I think we support it. Simply don't use null.
use this: `date('startDate')`

If not, try the latest version or knobs.

**Comment by Bamieh** [comment]
I am using the latest version.

not passing any defaults for `date` results in the following: `01/01/1970 2:00 AM`

**Comment by Bamieh** [comment]
probably a better approach is provide a "combination" knob, and add a "null" knob. then you can mid between different knob types, if this makes any sense?

**Comment by roonyh** [comment]
@Bamieh That is the unix epoch, which imo the expected value for a date for input `null`. Sorry but I could not understand what you mean by a "combination" knob and a "null" knob. Could you explain how you expect passing null to a date knob should work?

**Comment by Bamieh** [comment]
@roonyh
### Issue in hand

Sometimes react props are set to null by default for various reasons. However, there is no way to pass null as an option to the date knob, and possibly some other knobs.

### Current result:

*Passing null to date knob:*
>`startDate={date('startDate', null)}`
Result: `TypeError: Cannot read property 'getTime' of null`

*Passing nothing/undefined to date Knob:*
>`startDate={date('startDate')}`
Result: `01/01/1970`

### Expected result:
*Passing null to date knob:*
>`startDate={date('startDate', null)}`
Result: `null`

*Passing nothing/undefined to date Knob:*
>`startDate={date('startDate')}`
Result: `01/01/1970`

**Comment by arunoda** [comment]
@Bamieh yep. You are right.
We should accept null values too for the date.

Here's the related [code](https://github.com/kadirahq/storybook-addon-knobs/blob/master/src/index.js#L30) for this.
Send us a PR, if you can't wait until we fix this :)

**Comment by Bamieh** [comment]
@arunoda submitted
