### ISSUE TITLE
Error when accessing knobs outside a story

### ISSUE THREAD

**Issue by frederickfogerty** [kadirahq/storybook-addon-knobs#57]
Hi there - I'm trying to structure my stories as follows:

```tsx
const defaultProps = {
  onChecked: action('onChecked'),
  checked: knobs.boolean('checked', false),
};

storiesOf('primitives.Switch')
  .addDecorator(knobs.withKnobs)
  .add('dark', () => {
    return (
      <CenteredView>
        <Switch
          {...defaultProps}
          />
      </CenteredView>
    );
  })
  .add('light', () => {
    return (
      <CenteredView>
        <Switch
          theme='light'
          {...defaultProps}
          />
      </CenteredView>
    );
  });
```

But I receive the following error: `null is not an object (evaluating 'knobStore.get')`
![image](https://cloud.githubusercontent.com/assets/615334/19138891/882f5eda-8bdc-11e6-8194-dece47dffb1a.png)

Is this a pattern you endorse, is there an alternative you'd propose to share props between components?

Thanks! 🙌

**Comment by arunoda** [comment]
This is something nice and we can recommend it with a one little modification. Get default props with a function like:

```js
const getDefaultProps = () => ({
  onChecked: action('onChecked'),
  checked: knobs.boolean('checked', false),
});
```

The thing is we use some environment stuff managed by the decorator of knobs. So, it's only available inside a story.

**Comment by frederickfogerty** [comment]
So basically a factory, alright. I'll verify this and close if it works for me.

**Comment by frederickfogerty** [comment]
Yep, works for me!

**Comment by arunoda** [comment]
Great.
