### ISSUE TITLE
How to connect state and knobs to each other

### ISSUE THREAD

**Issue by mustafacam00** [kadirahq/storybook-addon-knobs#98]
I tried something like this but I got an error

error:
TypeError: Cannot read property 'get' of null

my reducer:
![image](https://cloud.githubusercontent.com/assets/6636963/26523223/7c947a50-431b-11e7-935f-2889c1151211.png)

**Comment by mustafacam00** [comment]
@arunoda

**Comment by shilman** [comment]
@mustafacam00 this repository is deprecated since we've migrated to `@storybook` npm package.

Please try out Storybooks 3.0: https://medium.com/storybookjs/announcing-storybook-3-0-329748b8f4cd

Then take the conversation to: https://github.com/storybooks/storybook
