### ISSUE TITLE
Array knob of empty string converts to an array of [""]

### ISSUE THREAD

**Issue by pmwisdom** [kadirahq/storybook-addon-knobs#99]
When I add an empty array knob to a component, aka:

`array('Label', [])` it shows correctly in the knob panel that its empty, and the component receives the prop `[]`, but when I add an error (say, `hello, world`, which converts to `['hello', 'world']` correctly) and then delete the string from the knob panel (back to `""`) my component receives `[""]`, when it should receive `[]`.

My solution for this is to create a patched component, but I believe this to be a bug.

Example workaround:

```` javascript
//patched-array.js
import {array} from '@storybook/addon-knobs';

const removeEmptyEntries = arr => {
	return arr.filter(e => Boolean(e));
};

const patchedArray = (name, value) => {
	return removeEmptyEntries(array(name, value));
};

export default patchedArray;
````

**Comment by shilman** [comment]
@pmwisdom this is a deprecated repo. Please post issues to https://github.com/storybooks/storybook. Thanks for using Storybook!

**Comment by pmwisdom** [comment]
Doh! Thanks.
